version: 2

sources:
  - name: staging
    database: terraform-demo-447612
    schema: taxi_data

    tables:
      - name: green_taxi_data_2024
      -  name: materialized_yellow_taxi_data_2024

